<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SkyScope</AssemblyName>
    <StartupObject>SkyScope.UI.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyScope.Core\SkyScope.Core.csproj" />
    <ProjectReference Include="..\SkyScope.Models\SkyScope.Models.csproj" />
  </ItemGroup>

</Project>
