; Beautiful Females NPC Overhaul - appearance rules
filterByNpcs=Skyrim.esm|00019E0C:copyVisualStyle=BeautifulFemales.esp|000800
filterByNpcs=Skyrim.esm|0001A697:copyVisualStyle=BeautifulFemales.esp|000801
filterByNpcs=Skyrim.esm|0002998E:skin=BeautifulFemales.esp|000802
filterByNpcs=Skyrim.esm|000A2C8E:skin=BeautifulFemales.esp|000803
