; Serana Redesign - conflicts with BeautifulFemales on Serana (0001A697)
filterByNpcs=Skyrim.esm|0001A697:copyVisualStyle=SeranaRedesign.esp|000900
filterByNpcs=Skyrim.esm|0001A697:skin=SeranaRedesign.esp|000901
