; Enhanced Character Outfits
filterByNpcs=Skyrim.esm|00019E0C,Skyrim.esm|0001A697:outfitDefault=EnhancedCharacterOutfits.esp|000A00
filterByNpcs=Skyrim.esm|000A2C8E:outfitDefault=EnhancedCharacterOutfits.esp|000A01
