; Winter Dawn Fashions - conflicts with EnhancedCharacterOutfits on Lydia (00019E0C)
filterByNpcs=Skyrim.esm|000AE779,Skyrim.esm|000AE77B:outfitDefault=WinterDawn_Fashions.esp|FE000962
filterByNpcs=Skyrim.esm|00019E0C:outfitDefault=WinterDawn_Fashions.esp|FE000963
